# filepath: .golangci.yml
run:
  concurrency: 4

linters-settings:
  goimports:
    local-prefixes: github.com/netwalker2000/finflow-wallet 

  staticcheck:
    checks: ["all"] 

  errcheck:
    check-type-assertions: true
    check-blank: true


  unparam:
    check-exported: false 

linters:
  disable-all: true 
  enable: 
    - gofmt
    - goimports
    - govet
    - staticcheck
    - unparam
    - gosimple
    - unused
    - typecheck
    - gosec
    - nakedret
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

issues:
  exclude-dirs: 
    - migrations
    - vendor
  exclude-rules:
    - path: _test\.go$ 
      linters:
        - gosec
        - revive
    - text: "should have a package comment" 
      linters:
        - revive
      source: "^package main$" 

  max-issues-per-linter: 0
  max-same-issues: 0